#!/usr/bin/env bash
# Propagate the cop repo (master) to the thief repo, deterministically.
#
# The thief branch is NOT rebased. Both branches edit README section 0, so a
# rebase conflicts on every run, and resolving it by hand has already produced
# a half-converted README once. Instead the thief branch is REBUILT from
# master and its README REGENERATED by scripts/thief_readme.py, which fails
# loudly if any anchor stops matching.
#
# Pushing is opt-in. This force-updates master and a tag on TWO remotes, so it
# will not do that unless you ask: run without --push to rehearse.
#
#   scripts/sync_repos.sh            # local rebuild + test gate, no pushes
#   scripts/sync_repos.sh --push     # ...then update both remotes
set -euo pipefail

COP_REMOTE=${COP_REMOTE:-origin}
THIEF_REMOTE=${THIEF_REMOTE:-thief}
THIEF_BRANCH=thief-submission
TAG=v1.0-submission
THIEF_TAG=${TAG}-thief
PYTEST=${PYTEST:-.venv/bin/python -m pytest}

PUSH=0
SKIP_TESTS=0
for arg in "$@"; do
  case "$arg" in
    --push) PUSH=1 ;;
    --skip-tests) SKIP_TESTS=1 ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

say() { printf '\n== %s\n' "$*"; }
die() { printf 'sync_repos: %s\n' "$*" >&2; exit 1; }

# --- preconditions -----------------------------------------------------------
say "checking preconditions"
[ -n "$(git status --porcelain)" ] && die "working tree is dirty; commit or stash first"
[ "$(git branch --show-current)" = "master" ] || die "run this from master"
git remote get-url "$COP_REMOTE"   >/dev/null || die "no remote '$COP_REMOTE'"
git remote get-url "$THIEF_REMOTE" >/dev/null || die "no remote '$THIEF_REMOTE'"
echo "ok: clean tree on master, both remotes present"

gate() {  # $1 = label
  if [ "$SKIP_TESTS" -eq 1 ]; then
    echo "WARNING: test gate skipped for $1"
    return
  fi
  say "test gate ($1)"
  $PYTEST -q | tail -2
  say "line-limit audit ($1)"
  local bad=0
  while read -r f; do
    [ "$(wc -l < "$f")" -gt 150 ] && { echo "OVER 150: $f"; bad=1; }
  done < <(git ls-files '*.py')
  [ "$bad" -eq 0 ] || die "line-limit violation on $1"
  echo "ok: no tracked .py over 150 lines"
}

# --- 1. gate master ----------------------------------------------------------
gate master
MASTER=$(git rev-parse master)

# --- 2. rebuild the thief branch from master --------------------------------
say "rebuilding $THIEF_BRANCH from master ($(git rev-parse --short master))"
git checkout -q -B "$THIEF_BRANCH" master
.venv/bin/python scripts/thief_readme.py README.md
git add README.md
git commit -q -m "docs: regenerate README for zero-trust-thief

Derived from cop master $(git rev-parse --short "$MASTER") by
scripts/thief_readme.py. Regenerated rather than rebased: both branches edit
section 0, so a rebase conflicts every time."
echo "ok: $THIEF_BRANCH at $(git rev-parse --short HEAD)"

# --- 3. gate the thief branch too -------------------------------------------
gate "$THIEF_BRANCH"

# --- 4. tags -----------------------------------------------------------------
say "moving tags"
git tag -f -a "$TAG" "$MASTER" -m "$TAG — zero-trust-cop" >/dev/null
git tag -f -a "$THIEF_TAG" "$THIEF_BRANCH" -m "$TAG — zero-trust-thief" >/dev/null
echo "ok: $TAG -> $(git rev-list -n1 "$TAG" | cut -c1-7), $THIEF_TAG -> $(git rev-list -n1 "$THIEF_TAG" | cut -c1-7)"

git checkout -q master

# --- 5. push (opt-in) --------------------------------------------------------
if [ "$PUSH" -eq 0 ]; then
  say "DRY RUN — nothing pushed. Re-run with --push to update both remotes."
  exit 0
fi

say "pushing"
git push "$COP_REMOTE" master
git push --force "$COP_REMOTE" "$TAG"
git push --force "$THIEF_REMOTE" "$THIEF_BRANCH:master"
git push --force "$THIEF_REMOTE" "$THIEF_TAG:refs/tags/$TAG"
# ...and under its own name too, so the thief-edition tag cannot rot one sync
# behind. It is deliberately NOT pushed to the cop remote, where the commit it
# points at is unreachable from master and the tag is pure noise.
git push --force "$THIEF_REMOTE" "$THIEF_TAG"

# --- 6. verify the remotes actually agree ------------------------------------
say "verifying remotes"
cop_head=$(git ls-remote --heads "$COP_REMOTE" master | cut -f1)
cop_tag=$(git ls-remote --tags "$COP_REMOTE" "${TAG}^{}" | cut -f1)
thief_head=$(git ls-remote --heads "$THIEF_REMOTE" master | cut -f1)
thief_tag=$(git ls-remote --tags "$THIEF_REMOTE" "${TAG}^{}" | cut -f1)

printf '  %-6s master=%s tag=%s\n' cop   "${cop_head:0:7}"   "${cop_tag:0:7}"
printf '  %-6s master=%s tag=%s\n' thief "${thief_head:0:7}" "${thief_tag:0:7}"

[ "$cop_head" = "$cop_tag" ]     || die "cop tag does not point at cop master"
[ "$thief_head" = "$thief_tag" ] || die "thief tag does not point at thief master"
[ "$cop_head" = "$MASTER" ]      || die "cop master is not the commit we gated"
[ "$cop_head" != "$thief_head" ] || die "both remotes identical — thief README did not apply"

say "done: both remotes updated and tag-aligned"
